version: '3.8'
services:
  app:
    image:aspnet-app
    ports:
      -"80:80"
    environment:
      -ACCEPT_EULA=Y
      -SA_PASSWORD=your!strongpassword

  mssql:
    image:mcr.microsoft.com/mssql/server:2019-latest
    restart:always
    enivironment:
      -ACCEPT_EULA=Y
      -SQ_PASSWORD=YOURSTRONG!PASSWORD
    ports:
      -"1433:1433"
    healthcheck:
      test:["CMD-SHELL","/opt/mssql-tools/bin/sqlcmd-S localhost-Usa -PyourstrongPassword 
      -Q'SELECT 1'||exit 1"]
        intervals:10s
        retries:10
        start_period:10s
        timeout:5s
